### ISSUE TITLE
Crash when adding some pleroma instances

### ISSUE THREAD

**Issue by fgaz** [donpdonp/zootdeck#4]
To reproduce, add the hostname of a pleroma instance. Weirdly, only some instances cause the error, for example among the ones listed at https://pleroma.social, cdrom.tokyo causes a crash, while stereophonic.space doesn't.

The error is always of the form:

```
[...]
photoback! acct foo@bar.baz type image/jpeg size 40269
MKDIR ./cache/foo@bar.baz
thread 277397 panic: attempt to unwrap error: AccessDenied
```

The `cache` directory does get created, but with weird permissions and sticky bit set:

```
$ ls -ld cache
d-w----r-T 1 fgaz users        0 Jun 18 11:38 cache
```

edit:
workaround: create `cache` with `mkdir cache` before running the program

**Comment by donpdonp** [comment]
thanks for bringing that up. I've run into that before but didnt find the root cause until now. The permissions were specified with `0644` for octal but zig uses `0o644`.

`db/file.zig: std.os.mkdir(cache_dir, 0o644) catch |err| {`
